trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: 'avantgarde\avantgarde.sln'
  buildPlatform: 'x86'
  buildConfiguration: 'Release'
  appxPackageDir: 'avantgarde\AppxPackages\\'

steps:
- task: NuGetToolInstaller@0

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    platform: 'x86'
    solution: '$(solution)'
    configuration: '$(buildConfiguration)'
    msbuildArgs: '/p:AppxBundlePlatforms="$(buildPlatform)" /p:AppxPackageDir="$(appxPackageDir)" /p:AppxBundle=Always /p:UapAppxPackageBuildMode=StoreUpload'
